import {
  Search,
  Clock3,
  RefreshCcw,
  HandCoins,
  ShieldCheck,
  Leaf,
} from "lucide-react";

export const dashboardMenus = [
  {
    title: "RECRUITMENT",
    description:
      "Recruitment, onboarding, medical, documents and employee records.",
    path: "/recruitment",
    icon: Search,
    iconColor: "text-blue-500",
    titleColor: "text-blue-600",
    lineColor: "bg-blue-300",
    buttonBorder: "border-blue-300",
    buttonText: "text-blue-600",
    bottomBar: "bg-blue-500",
    bgTint: "bg-blue-50",
  },
  {
    title: "ATTENDANCE",
    description:
      "Attendance monitoring, leave, overtime, shifts and payroll processing.",
    path: "/attendance",
    icon: Clock3,
    iconColor: "text-green-500",
    titleColor: "text-green-600",
    lineColor: "bg-green-300",
    buttonBorder: "border-green-300",
    buttonText: "text-green-600",
    bottomBar: "bg-green-500",
    bgTint: "bg-green-50",
  },
  {
    title: "EMPLOYEE MOVEMENT",
    description:
      "Promotion, transfer, increment, confirmation and other employee movements.",
    path: "/employee-movement",
    icon: RefreshCcw,
    iconColor: "text-orange-500",
    titleColor: "text-orange-500",
    lineColor: "bg-orange-300",
    buttonBorder: "border-orange-300",
    buttonText: "text-orange-500",
    bottomBar: "bg-orange-500",
    bgTint: "bg-orange-50",
  },
  {
    title: "SETTLEMENT",
    description:
      "Final settlement, compensation, gratuity, encashment and resignation settlement.",
    path: "/settlement",
    icon: HandCoins,
    iconColor: "text-cyan-500",
    titleColor: "text-cyan-600",
    lineColor: "bg-cyan-300",
    buttonBorder: "border-cyan-300",
    buttonText: "text-cyan-600",
    bottomBar: "bg-cyan-500",
    bgTint: "bg-cyan-50",
  },
  {
    title: "COMPLIANCE",
    description:
      "Legal compliance, CAP, audit management and regulatory requirements.",
    path: "/compliance",
    icon: ShieldCheck,
    iconColor: "text-violet-500",
    titleColor: "text-violet-600",
    lineColor: "bg-violet-300",
    buttonBorder: "border-violet-300",
    buttonText: "text-violet-600",
    bottomBar: "bg-violet-500",
    bgTint: "bg-violet-50",
  },
  {
    title: "SUSTAINABILITY",
    description:
      "ESG management, sustainability initiatives, reporting and performance tracking.",
    path: "/sustainability",
    icon: Leaf,
    iconColor: "text-lime-600",
    titleColor: "text-green-600",
    lineColor: "bg-green-300",
    buttonBorder: "border-green-300",
    buttonText: "text-green-600",
    bottomBar: "bg-green-600",
    bgTint: "bg-green-50",
  },
];